<a href="https://colab.research.google.com/github/tz2004a/sklearnWork/blob/Google-Colab-Notebooks/Copy_of_Question_2_Oversampling_and_Undersampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
%pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#2
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import svm
from sklearn.datasets import fetch_openml
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X

In [ ]:
# Normal CrossVal Decision Tree (Control) (#3)
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_test, y_test)
from sklearn.model_selection import cross_val_score
scoresDT = cross_val_score(clf, X_train, y_train, cv=10)
scoresDT

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.84507042, 0.83098592, 0.77464789, 0.76056338, 0.77464789,
       0.78873239, 0.81428571, 0.8       , 0.81428571, 0.77142857])

In [ ]:
# Getting the AUC for the Normal Decision Tree
from sklearn.metrics import roc_auc_score
cross_val_score(clf, X_train, y_train, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X_train, y_train, cv=10, scoring='roc_auc_ovo').var()

0.0014838995935388458

In [ ]:
#Getting the data for the Normal CrossVal Decision Tree (Control)
Y_test_pred = clf.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_test_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       224
           2       1.00      1.00      1.00       125

    accuracy                           1.00       349
   macro avg       1.00      1.00      1.00       349
weighted avg       1.00      1.00      1.00       349



In [ ]:
# Getting the GMean for the Normal Decision Tree
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_test, Y_test_pred)

1.0

In [ ]:
y_test

380    1
117    2
974    1
261    2
921    1
      ..
402    1
56     2
518    1
907    2
384    1
Name: Class, Length: 349, dtype: category
Categories (2, object): ['1', '2']

In [ ]:
# Normal CrossVal MLP (Control) (#4)
#WORKING MLP
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_test, y_test)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP
#accuracyScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
#accuracyScores
#errorScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='neg_mean_absolute_error')
#errorScores

In [ ]:
# Getting the AUC for the Normal CrossVal MLP
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X_train, y_train, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X_train, y_train, cv=10, scoring='roc_auc_ovo').var()

0.0005507799353994178

In [ ]:
#Getting the data for the Normal CrossVal MLP (Control)
Y_test_pred = clf.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_test_pred))

              precision    recall  f1-score   support

           1       0.98      0.98      0.98       234
           2       0.96      0.97      0.96       115

    accuracy                           0.97       349
   macro avg       0.97      0.97      0.97       349
weighted avg       0.97      0.97      0.97       349



In [ ]:
# Getting the GMean for the Normal MLP
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_test, Y_test_pred)

0.9719017893137911

In [ ]:
# Reset the data (X) #5
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X

# Original State of the Data
from collections import Counter
X.shape
print(sorted(Counter(X['y']).items()))

[('1', 699), ('2', 356)]


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
# Prepping for oversampling test #6
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

#OVERSAMPLING
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled['y'].value_counts()

[('1', 699), ('2', 699)] (1398,)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


1    699
2    699
Name: y, dtype: int64

In [ ]:
#Oversampling 10-fold-Crossvalidation part 2 #7
##Decision Tree Classifier
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_resampled_test, y_resampled_test)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scores_undersample_DT

#X, y = fetch_openml('qsar-biodeg', return_X_y=True)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
#clf = DecisionTreeClassifier().fit(X_test, y_test)
#from sklearn.model_selection import cross_val_score
#scoresDT = cross_val_score(clf, X_train, y_train, cv=10)
#scoresDT

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Getting the AUC for Oversampling Decision Tree Classifier
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').var()

0.0

In [ ]:
Y_test_pred.shape

(462,)

In [ ]:
#Getting the data for the oversampling decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       229
           2       1.00      1.00      1.00       233

    accuracy                           1.00       462
   macro avg       1.00      1.00      1.00       462
weighted avg       1.00      1.00      1.00       462



In [ ]:
# Getting the GMean for the oversampling decision tree classifier
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

1.0

In [ ]:
X #just a quick check to see what X is

In [ ]:
#Oversampling 10fold cross validation
##MLP
#Prep
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

#OVERSAMPLING
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled['y'].value_counts()

[('1', 699), ('2', 699)] (1398,)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


1    699
2    699
Name: y, dtype: int64

In [ ]:
X_resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
X_resampled_train

In [ ]:
#CORRECTLY!!!!
#Oversampling 10-fold crossvalidation part 2
# MLP Classifier

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X_resampled, y_resampled = ros.fit_resample(X, Y)

X_resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_resampled_train, y_resampled_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_resampled_train, y_resampled_train, cv=10)
scoresMLP

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.90425532, 0.85106383, 0.90425532, 0.86170213, 0.87234043,
       0.87234043, 0.84946237, 0.84946237, 0.82795699, 0.82795699])

In [ ]:
# Getting the AUC for Oversampling MLP Classifier
from sklearn.metrics import roc_auc_score
cross_val_score(clf, X_resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').mean()
#cross_val_score(clf, X_resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').var()

0.9321776526856536

In [ ]:
#Getting the data for the oversampling MLP classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

              precision    recall  f1-score   support

           1       0.89      0.87      0.88       232
           2       0.87      0.90      0.88       230

    accuracy                           0.88       462
   macro avg       0.88      0.88      0.88       462
weighted avg       0.88      0.88      0.88       462



In [ ]:
# Getting the GMean for the oversampling MLP classifier
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

0.8808941552443337

In [ ]:
y_resampled_test

899     2
992     1
1146    2
451     1
312     1
       ..
280     2
1355    2
149     2
99      2
1213    2
Name: y, Length: 462, dtype: category
Categories (2, object): ['1', '2']

In [ ]:
#Oversampling 10-fold-crossvalidation part 2
#MLP Classifier

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.83098592, 0.85915493, 0.83098592, 0.83098592, 0.84507042,
       0.84507042, 0.78571429, 0.8       , 0.85714286, 0.91428571])

In [ ]:
#UNDERSAMPLING
#Prep
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled
X_resampled['y'].value_counts()
X_resampled

In [ ]:
#UNDERSAMPLING 10fold cross validation
##Decision Tree Classifier
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_resampled_test, y_resampled_test)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scores_undersample_DT

#Getting the data for the undersampling decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

In [ ]:
# Getting the AUC for Undersampling Decision Tree Classifier
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').var()

0.0

In [ ]:
# Getting the GMean for the Undersampling Decision Tree classifier
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

1.0

In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (WRONG WAY!!!)
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores
#accuracyScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
#accuracyScores

array([1.        , 0.875     , 0.75      , 1.        , 0.875     ,
       1.        , 0.85714286, 0.85714286, 0.85714286, 1.        ])

In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (THE RIGHT WAY!!!!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP

#Getting the data for the undersampling MLP
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.85915493, 0.81690141, 0.87323944, 0.88732394, 0.91549296,
       0.78873239, 0.84285714, 0.82857143, 0.9       , 0.75714286])

In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (THE REAL DEAL!!! IGNORE THE OTHERS!!!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_resampled, y_resampled = ros.fit_resample(X, Y)

X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X__resampled_train, y_resampled_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scoresMLP

#Getting the data for the undersampling MLP
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


              precision    recall  f1-score   support

           1       0.95      0.84      0.89       235
           2       0.85      0.95      0.90       227

    accuracy                           0.89       462
   macro avg       0.90      0.89      0.89       462
weighted avg       0.90      0.89      0.89       462



In [ ]:
# Getting the GMean for the Undersampling MLP
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

0.8931268154537291

In [ ]:
# Getting the AUC for Undersampling MLP
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10, scoring='roc_auc_ovo').var()

0.000723571796786446

In [ ]:
# Install SMOTE
%pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#SMOTE Oversampling
# Prepping the data
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

#smote declaration
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=2)
X_train_res, y_train_res = smote.fit_resample(X_train.astype('float'), y_train.astype('float'))

#Proof that SMOTE worked by comparing the original and after
from collections import Counter
print("Before :", Counter(y_train))
print("After :", Counter(y_train_res))



Before : Counter({'1': 478, '2': 228})
After : Counter({2.0: 478, 1.0: 478})


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
y_train

In [ ]:
#SMOTE Decision Tree Classifier (remember to run the previous segment before this!)
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_train_res, y_train_res, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_train_res, y_train_res)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X_train_res, y_train_res, cv=10)
scores_undersample_DT

#Getting the data for the SMOTE decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

#Y_Test_Pred = clf.predict(X_test)
#pd.crosstab(pd.Series(Y_Test_Pred, name = 'Predicted'),
#            pd.Series(y_test['y'], name= 'Actual'))
#from sklearn.metrics import classification_report
#classification_report(y_test, Y_Test_Pred)

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       156
         2.0       1.00      1.00      1.00       153

    accuracy                           1.00       309
   macro avg       1.00      1.00      1.00       309
weighted avg       1.00      1.00      1.00       309



In [ ]:
# Getting the GMean for the SMOTE Decision Tree Classifier
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

1.0

In [ ]:
# Getting the AUC for SMOTE Decision Tree Classifier
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='roc_auc_ovo').var()

0.0

In [ ]:
X_train

In [ ]:
#SMOTE MLP (remember to run the previous previous segment before this!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
#X, y = fetch_openml('qsar-biodeg', return_X_y=True)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_train_res, y_train_res, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train_res, y_train_res)

from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train_res, y_train_res, cv=10)
scoresMLP

#Getting the data for the SMOTE decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       166
         2.0       1.00      1.00      1.00       150

    accuracy                           1.00       316
   macro avg       1.00      1.00      1.00       316
weighted avg       1.00      1.00      1.00       316



In [ ]:
# Getting the GMean for the SMOTE MLP
from imblearn.metrics import geometric_mean_score
geometric_mean_score(y_resampled_test, Y_test_pred)

1.0

In [ ]:
# Getting the AUC for SMOTE MLP
from sklearn.metrics import roc_auc_score
#cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='roc_auc_ovo').mean()
cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='roc_auc_ovo').var()

0.0

In [ ]:
y_test

NameError: ignored