<a href="https://colab.research.google.com/github/tz2004a/sklearnWork/blob/Google-Colab-Notebooks/Question_2_Oversampling_and_Undersampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
%pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#2
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import svm
from sklearn.datasets import fetch_openml
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


V1      V2   V3   V4    V5   V6   V7    V8   V9  V10  ...  V33   V34  \
0     3.919  2.6909  0.0  0.0   0.0  0.0  0.0  31.4  2.0  0.0  ...  0.0   0.0   
1     4.170  2.1144  0.0  0.0   0.0  0.0  0.0  30.8  1.0  1.0  ...  0.0   0.0   
2     3.932  3.2512  0.0  0.0   0.0  0.0  0.0  26.7  2.0  4.0  ...  0.0   0.0   
3     3.000  2.7098  0.0  0.0   0.0  0.0  0.0  20.0  0.0  2.0  ...  0.0   0.0   
4     4.236  3.3944  0.0  0.0   0.0  0.0  0.0  29.4  2.0  4.0  ...  0.0   0.0   
...     ...     ...  ...  ...   ...  ...  ...   ...  ...  ...  ...  ...   ...   
1050  5.431  2.8955  0.0  0.0   0.0  2.0  0.0  32.1  4.0  1.0  ...  0.0   6.0   
1051  5.287  3.3732  0.0  0.0   9.0  0.0  0.0  35.3  0.0  9.0  ...  0.0   3.0   
1052  4.869  1.7670  0.0  1.0   9.0  0.0  5.0  44.4  0.0  4.0  ...  4.0  13.0   
1053  5.158  1.6914  2.0  0.0  36.0  0.0  9.0  56.1  0.0  0.0  ...  1.0  16.0   
1054  5.076  2.6588  2.0  0.0   0.0  0.0  4.0  54.5  0.0  0.0  ...  2.0   0.0   

      V35    V36    V37  V38     V39  V40  V41  y  
0     0.0  2.949  1.591  0.0   7.253  0.0  0.0  2  
1     0.0  3.315  1.967  0.0   7.257  0.0  0.0  2  
2     1.0  3.076  2.417  0.0   7.601  0.0  0.0  2  
3     1.0  3.046  5.000  0.0   6.690  0.0  0.0  2  
4     0.0  3.351  2.405  0.0   8.003  0.0  0.0  2  
...   ...    ...    ...  ...     ...  ...  ... ..  
1050  1.0  3.573  2.242  1.0   8.088  0.0  0.0  1  
1051  0.0  3.787  3.083  3.0   9.278  0.0  0.0  1  
1052  0.0  3.848  2.576  5.0   9.537  1.0  0.0  1  
1053  0.0  5.808  2.055  8.0  11.055  0.0  1.0  1  
1054  0.0  4.009  2.206  0.0   9.130  0.0  2.0  1  

[1055 rows x 42 columns]

In [ ]:
# Normal CrossVal Decision Tree (Control) (#3)
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_test, y_test)
from sklearn.model_selection import cross_val_score
scoresDT = cross_val_score(clf, X_train, y_train, cv=10)
scoresDT

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.76056338, 0.87323944, 0.83098592, 0.76056338, 0.8028169 ,
       0.76056338, 0.81428571, 0.81428571, 0.84285714, 0.74285714])

In [ ]:
# Normal CrossVal MLP (Control) (#4)
#WORKING MLP
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_test, y_test)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP
#accuracyScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
#accuracyScores
#errorScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='neg_mean_absolute_error')
#errorScores

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.83098592, 0.83098592, 0.87323944, 0.84507042, 0.90140845,
       0.81690141, 0.82857143, 0.84285714, 0.81428571, 0.91428571])

In [ ]:
# Reset the data (X) #5
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X

# Original State of the Data
from collections import Counter
X.shape
print(sorted(Counter(X['y']).items()))

[('1', 699), ('2', 356)]


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
# Prepping for oversampling test #6
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

#OVERSAMPLING
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled['y'].value_counts()

[('1', 699), ('2', 699)] (1398,)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


1    699
2    699
Name: y, dtype: int64

In [ ]:
#Oversampling 10-fold-Crossvalidation part 2 #7
##Decision Tree Classifier
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_resampled_test, y_resampled_test)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scores_undersample_DT

#X, y = fetch_openml('qsar-biodeg', return_X_y=True)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
#clf = DecisionTreeClassifier().fit(X_test, y_test)
#from sklearn.model_selection import cross_val_score
#scoresDT = cross_val_score(clf, X_train, y_train, cv=10)
#scoresDT

array([0.88297872, 0.89361702, 0.88297872, 0.87234043, 0.88297872,
       0.87234043, 0.87096774, 0.89247312, 0.89247312, 0.8172043 ])

In [ ]:
X_resampled_test

V1      V2   V3   V4   V5   V6   V7    V8   V9  V10  ...  V32  V33  \
899   4.739  2.5436  0.0  0.0  0.0  0.0  0.0  35.7  1.0  2.0  ...  0.0  0.0   
992   4.629  3.9373  0.0  0.0  0.0  0.0  0.0  31.3  0.0  1.0  ...  0.0  0.0   
1146  5.120  3.2785  0.0  0.0  0.0  0.0  3.0  36.8  3.0  6.0  ...  0.0  0.0   
451   4.000  2.2551  0.0  0.0  0.0  0.0  0.0  37.5  0.0  0.0  ...  0.0  0.0   
312   5.109  2.4912  4.0  0.0  2.0  0.0  8.0  44.8  0.0  0.0  ...  0.0  6.0   
...     ...     ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...  ...   
280   4.783  3.2726  0.0  0.0  2.0  0.0  2.0  38.9  0.0  1.0  ...  0.0  2.0   
1355  4.732  3.0836  0.0  0.0  0.0  0.0  1.0  46.7  0.0  2.0  ...  0.0  0.0   
149   4.732  3.3319  0.0  0.0  0.0  0.0  2.0  42.9  0.0  2.0  ...  0.0  2.0   
99    3.618  2.3911  0.0  0.0  0.0  0.0  0.0  25.0  2.0  0.0  ...  0.0  0.0   
1213  4.372  3.5554  0.0  0.0  0.0  0.0  0.0  29.2  2.0  3.0  ...  0.0  0.0   

      V34  V35    V36    V37  V38    V39  V40  V41  
899   0.0  0.0  3.547  2.306  0.0  8.108  0.0  0.0  
992   1.0  0.0  3.475  2.810  1.0  7.673  0.0  0.0  
1146  0.0  0.0  3.852  2.481  0.0  9.032  3.0  0.0  
451   0.0  0.0  3.175  1.667  0.0  7.081  0.0  0.0  
312   4.0  4.0  4.124  2.488  2.0  9.615  0.0  4.0  
...   ...  ...    ...    ...  ...    ...  ...  ...  
280   2.0  2.0  3.666  2.315  1.0  8.046  0.0  0.0  
1355  0.0  1.0  3.663  2.926  0.0  8.161  0.0  0.0  
149   0.0  2.0  3.670  2.917  0.0  8.008  0.0  0.0  
99    2.0  1.0  2.848  1.900  1.0  6.432  0.0  0.0  
1213  0.0  0.0  3.355  2.600  0.0  7.811  0.0  0.0  

[462 rows x 41 columns]

In [ ]:
#Getting the data for the oversampling decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

              precision    recall  f1-score   support

           1       0.91      0.90      0.90       226
           2       0.90      0.92      0.91       236

    accuracy                           0.91       462
   macro avg       0.91      0.91      0.91       462
weighted avg       0.91      0.91      0.91       462



In [ ]:
X #just a quick check to see what X is

V1      V2   V3   V4    V5   V6   V7    V8   V9  V10  ...  V32  V33  \
0     3.919  2.6909  0.0  0.0   0.0  0.0  0.0  31.4  2.0  0.0  ...  0.0  0.0   
1     4.170  2.1144  0.0  0.0   0.0  0.0  0.0  30.8  1.0  1.0  ...  0.0  0.0   
2     3.932  3.2512  0.0  0.0   0.0  0.0  0.0  26.7  2.0  4.0  ...  0.0  0.0   
3     3.000  2.7098  0.0  0.0   0.0  0.0  0.0  20.0  0.0  2.0  ...  0.0  0.0   
4     4.236  3.3944  0.0  0.0   0.0  0.0  0.0  29.4  2.0  4.0  ...  0.0  0.0   
...     ...     ...  ...  ...   ...  ...  ...   ...  ...  ...  ...  ...  ...   
1050  5.431  2.8955  0.0  0.0   0.0  2.0  0.0  32.1  4.0  1.0  ...  2.0  0.0   
1051  5.287  3.3732  0.0  0.0   9.0  0.0  0.0  35.3  0.0  9.0  ...  0.0  0.0   
1052  4.869  1.7670  0.0  1.0   9.0  0.0  5.0  44.4  0.0  4.0  ...  0.0  4.0   
1053  5.158  1.6914  2.0  0.0  36.0  0.0  9.0  56.1  0.0  0.0  ...  0.0  1.0   
1054  5.076  2.6588  2.0  0.0   0.0  0.0  4.0  54.5  0.0  0.0  ...  0.0  2.0   

       V34  V35    V36    V37  V38     V39  V40  V41  
0      0.0  0.0  2.949  1.591  0.0   7.253  0.0  0.0  
1      0.0  0.0  3.315  1.967  0.0   7.257  0.0  0.0  
2      0.0  1.0  3.076  2.417  0.0   7.601  0.0  0.0  
3      0.0  1.0  3.046  5.000  0.0   6.690  0.0  0.0  
4      0.0  0.0  3.351  2.405  0.0   8.003  0.0  0.0  
...    ...  ...    ...    ...  ...     ...  ...  ...  
1050   6.0  1.0  3.573  2.242  1.0   8.088  0.0  0.0  
1051   3.0  0.0  3.787  3.083  3.0   9.278  0.0  0.0  
1052  13.0  0.0  3.848  2.576  5.0   9.537  1.0  0.0  
1053  16.0  0.0  5.808  2.055  8.0  11.055  0.0  1.0  
1054   0.0  0.0  4.009  2.206  0.0   9.130  0.0  2.0  

[1055 rows x 41 columns]

In [ ]:
#Oversampling 10fold cross validation
##MLP
#Prep
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

#OVERSAMPLING
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled['y'].value_counts()

[('1', 699), ('2', 699)] (1398,)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


1    699
2    699
Name: y, dtype: int64

In [ ]:
X_resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
X_resampled_train

In [ ]:
#CORRECTLY!!!!
#Oversampling 10-fold crossvalidation part 2
# MLP Classifier

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X_resampled, y_resampled = ros.fit_resample(X, Y)

X_resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_resampled_train, y_resampled_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_resampled_train, y_resampled_train, cv=10)
scoresMLP

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.92553191, 0.79787234, 0.89361702, 0.87234043, 0.89361702,
       0.91489362, 0.87096774, 0.91397849, 0.88172043, 0.91397849])

In [ ]:
#Getting the data for the oversampling MLP classifier
Y_test_pred = clf.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_test_pred))

              precision    recall  f1-score   support

           1       0.95      0.91      0.93       221
           2       0.86      0.91      0.89       128

    accuracy                           0.91       349
   macro avg       0.90      0.91      0.91       349
weighted avg       0.92      0.91      0.91       349



In [ ]:
y_test

825    1
389    1
615    1
62     2
261    2
      ..
278    2
466    1
431    1
904    2
973    1
Name: Class, Length: 349, dtype: category
Categories (2, object): ['1', '2']

In [ ]:
#Oversampling 10-fold-crossvalidation part 2
#MLP Classifier

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.83098592, 0.85915493, 0.83098592, 0.83098592, 0.84507042,
       0.84507042, 0.78571429, 0.8       , 0.85714286, 0.91428571])

In [ ]:
#UNDERSAMPLING
#Prep
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y

Y = X['y']
Y

from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(X, Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)
X_resampled
X_resampled['y'].value_counts()
X_resampled

[('1', 356), ('2', 356)] (712,)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


V1      V2   V3   V4   V5   V6   V7    V8   V9  V10  ...  V33  V34  \
0    5.192  4.4911  1.0  0.0  0.0  0.0  0.0  28.6  4.0  4.0  ...  0.0  0.0   
1    5.459  3.1356  1.0  0.0  2.0  0.0  4.0  41.7  0.0  3.0  ...  2.0  2.0   
2    3.414  3.4592  1.0  0.0  0.0  0.0  0.0  28.6  0.0  0.0  ...  0.0  0.0   
3    4.593  2.9033  0.0  0.0  3.0  0.0  1.0  38.9  0.0  1.0  ...  1.0  2.0   
4    5.870  2.7059  5.0  0.0  0.0  2.0  4.0  48.3  1.0  1.0  ...  2.0  0.0   
..     ...     ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...  ...   
707  5.072  2.5240  0.0  0.0  0.0  0.0  2.0  36.4  2.0  4.0  ...  0.0  0.0   
708  5.089  1.8308  0.0  0.0  0.0  0.0  2.0  40.0  0.0  4.0  ...  0.0  0.0   
709  4.910  2.8789  0.0  0.0  0.0  0.0  3.0  52.6  0.0  1.0  ...  1.0  0.0   
710  4.000  3.1669  0.0  0.0  0.0  0.0  0.0  45.5  0.0  0.0  ...  0.0  2.0   
711  4.977  2.0833  0.0  0.0  0.0  0.0  0.0  31.0  1.0  6.0  ...  0.0  0.0   

     V35    V36    V37  V38    V39  V40  V41  y  
0    1.0  4.433  2.213  0.0  9.217  0.0  0.0  1  
1    3.0  4.748  2.906  1.0  9.674  0.0  0.0  1  
2    0.0  3.844  2.792  1.0  8.128  0.0  0.0  1  
3    3.0  3.601  2.683  2.0  8.200  0.0  0.0  1  
4    1.0  4.280  2.586  0.0  9.741  0.0  5.0  1  
..   ...    ...    ...  ...    ...  ...  ... ..  
707  0.0  3.794  2.167  0.0  8.904  2.0  0.0  2  
708  0.0  3.800  2.222  0.0  8.910  2.0  0.0  2  
709  1.0  3.860  2.273  0.0  8.487  0.0  0.0  2  
710  0.0  3.482  2.167  1.0  7.627  0.0  0.0  2  
711  3.0  3.497  2.458  0.0  8.579  0.0  0.0  2  

[712 rows x 42 columns]

In [ ]:
#UNDERSAMPLING 10fold cross validation
##Decision Tree Classifier
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_resampled_test, y_resampled_test)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scores_undersample_DT

#Getting the data for the undersampling decision tree classifier
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       118
           2       1.00      1.00      1.00       117

    accuracy                           1.00       235
   macro avg       1.00      1.00      1.00       235
weighted avg       1.00      1.00      1.00       235



In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (WRONG WAY!!!)
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores
#accuracyScores = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
#accuracyScores

array([1.        , 0.875     , 0.75      , 1.        , 0.875     ,
       1.        , 0.85714286, 0.85714286, 0.85714286, 1.        ])

In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (THE RIGHT WAY!!!!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train, y_train, cv=10)
scoresMLP

#Getting the data for the undersampling MLP
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


array([0.85915493, 0.81690141, 0.87323944, 0.88732394, 0.91549296,
       0.78873239, 0.84285714, 0.82857143, 0.9       , 0.75714286])

In [ ]:
#UNDERSAMPLING 10fold cross validation
##MLP (THE REAL DEAL!!! IGNORE THE OTHERS!!!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
X_resampled, y_resampled = ros.fit_resample(X, Y)

X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X__resampled_train, y_resampled_train)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X__resampled_train, y_resampled_train, cv=10)
scoresMLP

#Getting the data for the undersampling MLP
Y_test_pred = clf.predict(X_resampled_test)
from sklearn.metrics import classification_report
print(classification_report(y_resampled_test, Y_test_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


NameError: ignored

In [ ]:
# Install SMOTE
%pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#SMOTE Oversampling
# Prepping the data
X, y = fetch_openml('qsar-biodeg', return_X_y=True)
df = X
df['y'] = y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

#smote declaration
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=2)
X_train_res, y_train_res = smote.fit_resample(X_train.astype('float'), y_train.astype('float'))

#Proof that SMOTE worked by comparing the original and after
from collections import Counter
print("Before :", Counter(y_train))
print("After :", Counter(y_train_res))



Before : Counter({'1': 479, '2': 227})
After : Counter({2.0: 479, 1.0: 479})


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
#SMOTE Decision Tree Classifier (remember to run the previous segment before this!)
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
#X__resampled_train, X_resampled_test, y_resampled_train, y_resampled_test = train_test_split(X_resampled, y_resampled, test_size=0.33)
clf = DecisionTreeClassifier().fit(X_train_res, y_train_res)

from sklearn.model_selection import cross_val_score
scores_undersample_DT = cross_val_score(clf, X_train_res, y_train_res, cv=10)
scores_undersample_DT

#Getting the data for the SMOTE decision tree classifier
Y_test_pred = clf.predict(X_train_res)
from sklearn.metrics import classification_report
print(classification_report(y_train_res, Y_test_pred))

#Y_Test_Pred = clf.predict(X_test)
#pd.crosstab(pd.Series(Y_Test_Pred, name = 'Predicted'),
#            pd.Series(y_test['y'], name= 'Actual'))
#from sklearn.metrics import classification_report
#classification_report(y_test, Y_Test_Pred)

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       477
         2.0       1.00      1.00      1.00       477

    accuracy                           1.00       954
   macro avg       1.00      1.00      1.00       954
weighted avg       1.00      1.00      1.00       954



In [ ]:
y_train_res

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
949    2.0
950    2.0
951    2.0
952    2.0
953    2.0
Name: Class, Length: 954, dtype: float64

In [ ]:
#SMOTE MLP (remember to run the previous previous segment before this!)
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
#X, y = fetch_openml('qsar-biodeg', return_X_y=True)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train_res, y_train_res)
from sklearn.model_selection import cross_val_score
scoresMLP = cross_val_score(clf, X_train_res, y_train_res, cv=10)
scoresMLP

#Getting the data for the SMOTE decision tree classifier
Y_test_pred = clf.predict(X_train_res)
from sklearn.metrics import classification_report
print(classification_report(y_train_res, Y_test_pred))

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       477
         2.0       1.00      1.00      1.00       477

    accuracy                           1.00       954
   macro avg       1.00      1.00      1.00       954
weighted avg       1.00      1.00      1.00       954



In [ ]:
y_test

938    1
761    1
237    2
598    1
121    2
      ..
911    1
317    1
796    1
771    1
253    2
Name: Class, Length: 349, dtype: category
Categories (2, object): ['1', '2']